Update check_api_versions.yml

diff --git a/.github/workflows/check_api_versions.yml b/.github/workflows/check_api_versions.yml
--- a/.github/workflows/check_api_versions.yml
+++ b/.github/workflows/check_api_versions.yml
@@ -38,24 +38,20 @@ jobs:
 
       - name: compare versions and push
         if: ${{ env.CURRENT < env.UPSTREAM }}
-        run: echo "${{ env.CURRENT }}" && echo "less than"
+#         run: echo "${{ env.CURRENT }}" && echo "less than"
 
+        run: |
+          echo ${CURRENT} && echo ${UPSTREAM}
+          if [[ $CURRENT < $UPSTREAM ]]; then
+            echo "newer API version detected"
+            sed -i "1s@^@${FULL_UPSTREAM}\\n@" api_versions.csv
+            git --no-pager diff
+            git config user.name github-actions
+            git config user.email github-actions@github.com
+            git add api_versions.csv
+            git commit -m "update api_versions"
+            git push
 
-
-#         run: |
-#           echo ${CURRENT} && echo ${UPSTREAM}
-#           if [[ $CURRENT < $UPSTREAM ]]; then
-#             echo "newer API version detected"
-#             sed -i "1s@^@${FULL_UPSTREAM}\\n@" api_versions.csv
-#             git --no-pager diff
-#             git config user.name github-actions
-#             git config user.email github-actions@github.com
-#             git add api_versions.csv
-#             git commit -m "update api_versions"
-#             git push
-#           else
-#             exit 1
-#           fi
-#       - name: no update
-#         if: ${{ env.CURRENT -ge env.UPSTREAM }}
-#         run: exit 1
+      - name: no update
+        if: ${{ env.CURRENT > env.UPSTREAM }}
+        run: echo "no update required" && exit 1
